name: Bump the version

on: [ pull_request ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on the PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const packageJson = require('./package.json');
            const fs = require("fs");

            // bump the version in the package.json
            let [major, minor, patch] = version.split('.');

            // leverage a case statment to bump the version base option.type
            switch (options.type) {
              case 'major':
                major++;
                minor = 0;
                patch = 0;
                break;
              case 'minor': 
                minor++;
                patch = 0;
                break;
              case 'patch':
                patch++;
                break;
              default:
                throw new Error(`Unknown version type: ${options.type}`);
            }

            const newVersion = [major, minor, patch].join('.');
            packageJson.version = newVersion;

            fs.writeFileSync("package.json", JSON.stringify(packageJson, null, 2));
