name: Bump the version

on: [ pull_request ]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install

      - name: bump the verion
        uses: actions/github-script@v4
        id: bumpVersion
        with:
          script: |
            const packageJson = require("./package.json");
            // const fs = require("fs");

            // bump the version in the package.json
            let [major, minor, patch] = packageJson.version.split('.');
            
            // replace this with the label
            let options = {type: "patch"}

            // leverage a case statment to bump the version base option.type
            switch (options.type) {
              case 'major':
                major++;
                minor = 0;
                patch = 0;
                break;
              case 'minor': 
                minor++;
                patch = 0;
                break;
              case 'patch':
                patch++;
                break;
              default:
                throw new Error(`Unknown version type: ${options.type}`);
            }

            const newVersion = [major, minor, patch].join('.');
            packageJson.version = newVersion;
            
            return packageJson

            // fs.writeFileSync("package.json", JSON.stringify(packageJson, null, 2));
      - uses: DamianReeves/write-file-action@v1.0
        with:
          path: ./package.json
          contents: ${{steps.bumpVersion.outputs.result}}
          write-mode: overwrite
#       - name: set git user
#         run: |
#             git config --global user.name ${GITHUB_ACTOR}
#             git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
#             git add package.json
#             git commit -m 'bump package version'
#       - name: Push changes
#         uses: ad-m/github-push-action@master
#         with:
#             github_token: ${{ secrets.GITHUB_TOKEN }}
#             branch: ${{ github.head_ref }}
#             force: true
