name: Bump the version

on: [ pull_request_target ]

permissions:
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - runs: node action/index.js
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
