name: "Comment run"
on:
  issue_comment:
    types: [created, edited]

jobs:
  comment-run:
    runs-on: ubuntu-18.04
    steps:
    - uses: bdougie/gipht-action@main
    - run: echo |
        Hello FLoridaJS

