on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: bdougie/leveuptutorials-action@main
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
