on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: bdougie/leveuptutorials-action@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
