name: Run a local file
on:
  workflow_dispatch:
  pull_request:

jobs:
  boop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: node action.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
