name: Party NOW!
on: issue_comment

jobs:
  party-line:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello is this thing on?"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.BDOUGIE_TOKEN }}
          script: |    
            console.log("CONTEXT:", JSON.stringify(context))

            if (context.payload.comment.body.includes(".party")) {
              github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id
              })

              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Click to go live! [party.opensauced.pizza](https://party.opensauced.pizza)!'
              })
            }
